// Hand-authored line definition for the real Treater Line 2.
// Authored from docs/REAL_LINE_SPECS.md; corrections from the engineer
// meeting are edits to this file, never to components.
//
// Coordinates are world units, side elevation, gravity-true: grain falls
// down the screen, elevators climb, what catches sits below what drops.
// Anchors are port positions relative to the machine origin (x, y).
//
// Tags marked TBC-nn were not legible / not present on the drawings; the
// real tags are an engineer-meeting question.

export const line = {
  zones: [
    { id: "treating", name: "TREATING" },
    { id: "packaging", name: "PACKAGING & OUTLOAD" },
    { id: "bagging", name: "BAGGING" },
  ],

  machines: [
    // ================= TREATING (sheet 52-12) =================
    {
      id: "upstreamStub",
      type: "stub",
      name: "from yellow-bin area · 52.414.E00",
      tag: "STUB.IN",
      status: "stub",
      zone: "treating",
      x: 60, y: 60, w: 8, h: 8,
      ports: { inputs: [], outputs: ["out"] },
      anchors: { out: { x: 4, y: 4 } },
    },
    {
      id: "treatMetalRemover",
      type: "metalRemover",
      name: "METAL REMOVER",
      tag: "TBC-01",
      status: "new",
      zone: "treating",
      x: 140, y: 90, w: 90, h: 50,
      ports: { inputs: ["in"], outputs: ["out", "waste"] },
      anchors: { in: { x: 0, y: 25 }, out: { x: 45, y: 50 }, waste: { x: 90, y: 40 } },
      labelAt: { x: 110, y: 14 },
      specs: [["role", "removes tramp metal before the buffer bin"]],
      questions: ["Real tag?", "Where does removed metal go?"],
    },
    {
      id: "metalRejectStub1",
      type: "stub",
      name: "metal reject · TBC",
      tag: "STUB.REJECT1",
      status: "stub",
      zone: "treating",
      x: 316, y: 156, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },
    {
      id: "treaterBufferBin",
      type: "bin",
      name: "TREATER BUFFER BIN",
      tag: "TBC-02",
      status: "relocated",
      zone: "treating",
      x: 140, y: 170, w: 170, h: 190,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 45, y: 0 }, out: { x: 85, y: 190 } },
      fill: 0.55,
      instruments: ["LT"],
      labelAt: { x: -6, y: -16 },
      params: [{ id: "level", label: "start level", min: 0, max: 100, value: 55, unit: "%" }],
      specs: [
        ["volume", "~7.7 m³ (~5.5 t) · LOW confidence read"],
        ["extras", "start-up area siren · bin level indication"],
        ["full name", "Treater Intermediary Buffer Bin"],
      ],
      questions: ["Confirm volume.", "Confirm level instrumentation (LT or switches?)."],
    },
    {
      id: "treatDrumFeeder",
      type: "drumFeeder",
      name: "INLET DRUM FEEDER",
      tag: "TBC-03",
      status: "new",
      zone: "treating",
      x: 185, y: 390, w: 80, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 40, y: 36 } },
      labelAt: { x: -160, y: 24 },
      params: [{ id: "rate", label: "feed rate", min: 0, max: 30, value: 20, unit: "t/h" }],
      specs: [["rate", "20 t/h"]],
      questions: ["Metering behaviour: how do the two opening positions work?"],
    },
    {
      id: "treatingElevator",
      type: "elevator",
      name: "BUCKET ELEVATOR · TREATING",
      tag: "TBC-19",
      status: "new",
      zone: "treating",
      x: 250, y: 222, w: 420, h: 240,
      geom: { colX: 200, duct: 36 },
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 25, y: 204 }, out: { x: 376, y: 44 } },
      instruments: ["ST"],
      labelAt: { x: 200, y: -14 },
      params: [{ id: "speed", label: "speed", min: 0, max: 100, value: 100, unit: "%" }],
      specs: [
        ["model", "Simatek E200 pendulum · 20 t/h"],
        ["buckets", "~176 × 20.5 L · chain ~105 m @ 10.08 m/min"],
        ["height", "~8731 mm · LOW confidence read"],
      ],
      questions: ["Real tag?", "Confirm bucket count / chain length (screenshot read)."],
    },
    {
      id: "treaterPreBin",
      type: "bin",
      name: "TREATER PRE-BIN",
      tag: "TBC-04",
      status: "new",
      zone: "treating",
      x: 590, y: 290, w: 90, h: 100,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 45, y: 0 }, out: { x: 45, y: 100 } },
      fill: 0.4,
      labelAt: { x: -10, y: -16 },
      specs: [["volume", "~1.62 m³ · LOW confidence read"]],
      questions: ["Confirm volume.", "Batch-feed logic into the treater?"],
    },
    {
      id: "batchTreater",
      type: "treater",
      name: "NIKLAS WNS/200 BATCH TREATER",
      tag: "TBC-05",
      status: "new",
      zone: "treating",
      x: 570, y: 420, w: 130, h: 110,
      ports: { inputs: ["in", "chemIn"], outputs: ["out", "wasteOut"] },
      anchors: {
        in: { x: 65, y: 0 },
        chemIn: { x: 130, y: 40 },
        out: { x: 30, y: 110 },
        wasteOut: { x: 100, y: 110 },
      },
      labelAt: { x: -160, y: 75 },
      params: [{ id: "batchRate", label: "treat rate", min: 4, max: 18, value: 18, unit: "t/h" }],
      specs: [
        ["type", "batch treater · ~4-18 t/h"],
        ["chemical", "from Formulation, sheet 52-15"],
        ["future", "powder dosing station (dashed on drawing)"],
        ["waste", "waste water to IBC tank"],
      ],
      questions: [
        "Batch size and cycle time (fill / treat / discharge)?",
        "What happens when downstream blocks mid-batch?",
        "Does treatment change bulk density?",
      ],
    },
    {
      id: "chemStub",
      type: "stub",
      name: "future: powder dosing station",
      tag: "STUB.CHEM",
      status: "stub",
      zone: "treating",
      x: 800, y: 450, w: 8, h: 8,
      ports: { inputs: [], outputs: ["out"] },
      anchors: { out: { x: 4, y: 4 } },
    },
    {
      id: "wasteWaterIbc",
      type: "ibc",
      name: "WASTE WATER IBC",
      tag: "TBC-06",
      status: "new",
      zone: "treating",
      x: 730, y: 560, w: 60, h: 46,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 30, y: 0 } },
      smallLabel: true,
      labelAt: { x: 70, y: 28 },
      questions: ["How is it emptied / how often?"],
    },
    {
      id: "treaterAfterBin",
      type: "bin",
      name: "TREATER AFTER-BIN",
      tag: "TBC-07",
      status: "new",
      zone: "treating",
      x: 540, y: 560, w: 80, h: 80,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 40, y: 80 } },
      fill: 0.3,
      labelAt: { x: -150, y: 30 },
      specs: [["volume", "~0.67 m³ · LOW confidence read"]],
      questions: ["Confirm volume (smooths batch discharge into continuous flow?)."],
    },
    {
      id: "scalpingScreen",
      type: "screen",
      name: "TREATMENT SCALPING SCREEN",
      tag: "52.602.F00",
      status: "new",
      zone: "treating",
      x: 620, y: 680, w: 140, h: 70,
      ports: { inputs: ["in"], outputs: ["out", "waste"] },
      anchors: { in: { x: 30, y: 0 }, out: { x: 140, y: 35 }, waste: { x: 70, y: 70 } },
      labelAt: { x: -210, y: 40 },
      params: [{ id: "wasteFrac", label: "scalpings split", min: 0, max: 20, value: 3, unit: "%" }],
      specs: [["capacity", "~64.4 t/h · LOW confidence read"]],
      questions: ["Typical scalpings fraction?", "Meaning of the 64.4 t/h figure?"],
    },
    {
      id: "discardBin",
      type: "metalBin",
      name: "DISCARD SCALPINGS BIN",
      tag: "TBC-08",
      status: "new",
      zone: "treating",
      x: 620, y: 790, w: 100, h: 80,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 50, y: 0 } },
      fill: 0.2,
      labelAt: { x: 0, y: 106 },
      questions: ["How is it emptied?"],
    },

    // ============ PACKAGING & OUTLOAD (sheet 52-13) ============
    {
      id: "proBoxStation",
      type: "proBox",
      name: "PRO BOX UNLOADING STATION",
      tag: "TBC-09",
      status: "new",
      zone: "packaging",
      x: 1140, y: 600, w: 120, h: 80,
      ports: { inputs: [], outputs: ["out"] },
      anchors: { out: { x: 60, y: 80 } },
      labelAt: { x: 0, y: -14 },
      questions: ["Operational role: returned boxed seed re-entering the line? Frequency?"],
    },
    {
      id: "inletDrumFeeder1",
      type: "drumFeeder",
      name: "INLET DRUM FEEDER 1",
      tag: "52.603.L00",
      status: "new",
      zone: "packaging",
      x: 1160, y: 730, w: 80, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 40, y: 36 } },
      labelAt: { x: -160, y: 24 },
      params: [{ id: "rate", label: "feed rate", min: 0, max: 30, value: 20, unit: "t/h" }],
      specs: [["rate", "20 t/h · 0.15 kW · MX drive"], ["controls", "2 opening positions (XV4/XV5) · empty cycle (XS4)"]],
      questions: ["Which feeder takes the Pro Box line vs the scalping screen line?"],
    },
    {
      id: "inletDrumFeeder2",
      type: "drumFeeder",
      name: "INLET DRUM FEEDER 2",
      tag: "52.603.L01",
      status: "new",
      zone: "packaging",
      x: 1290, y: 730, w: 80, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 40, y: 36 } },
      labelAt: { x: 90, y: 24 },
      params: [{ id: "rate", label: "feed rate", min: 0, max: 30, value: 20, unit: "t/h" }],
      specs: [["rate", "20 t/h · 0.15 kW · MX drive"]],
    },
    {
      id: "liftConveyor",
      type: "conveyor",
      name: "LIFT TO TOP CONVEYOR",
      tag: "52.604.E00",
      status: "new",
      zone: "packaging",
      x: 1170, y: 800, w: 220, h: 40,
      ports: { inputs: ["in1", "in2"], outputs: ["out"] },
      anchors: { in1: { x: 30, y: 0 }, in2: { x: 160, y: 0 }, out: { x: 215, y: 8 } },
      instruments: ["LSH"],
      labelAt: { x: 0, y: 64 },
      specs: [
        ["motor", "4.0 kW · MX drive"],
        ["extras", "safe start alarm (XA0) + start-up area siren"],
      ],
      questions: ["Confirm routing: drum feeders â†’ 52.604.E00 â†’ top conveyor (the one MED-confidence edge)."],
    },
    {
      id: "topConveyor",
      type: "conveyor",
      name: "TOP TRANSPORT CONVEYOR",
      tag: "52.605.X00",
      status: "new",
      zone: "packaging",
      x: 1440, y: 140, w: 1750, h: 26,
      ports: { inputs: ["in"], outputs: ["outBuffer", "outBinSeg", "outConcetti"] },
      anchors: {
        in: { x: 10, y: 20 },
        outBuffer: { x: 240, y: 26 },
        outBinSeg: { x: 1120, y: 26 },
        outConcetti: { x: 1745, y: 26 },
      },
      labelAt: { x: 560, y: -14 },
      params: [{ id: "speed", label: "speed", min: 0, max: 100, value: 100, unit: "%" }],
      specs: [["distribution", "3 branches: outload bins · big bag · Concetti"]],
      questions: [
        "Tag mapping unresolved (52.605.X00?): confirm.",
        "Are the three branches simultaneous or selected? What decides routing?",
      ],
    },
    {
      id: "outloadBufferBin",
      type: "bin",
      name: "OUTLOAD BUFFER BIN",
      tag: "52.701.H00",
      status: "new",
      zone: "packaging",
      x: 1650, y: 240, w: 130, h: 145,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 30, y: 0 }, out: { x: 65, y: 145 } },
      fill: 0.62,
      labelAt: { x: -190, y: 30 },
      specs: [["outlet valve", "52.701.V00 (relocated)"]],
      questions: ["Confirm volume (not stated on sheet 52-13)."],
    },
    {
      id: "packagingElevator",
      type: "elevator",
      name: "BUCKET ELEVATOR · PACKAGING",
      tag: "52.702.U00",
      status: "new",
      zone: "packaging",
      x: 1690, y: 196, w: 570, h: 240,
      geom: { colX: 264, duct: 36 },
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 25, y: 204 }, out: { x: 526, y: 44 } },
      instruments: ["ST"],
      labelAt: { x: 30, y: 296 },
      params: [{ id: "speed", label: "speed", min: 0, max: 100, value: 100, unit: "%" }],
      specs: [
        ["model", "Simatek E200 pendulum · 20 t/h"],
        ["motor", "5,0 kW · MX (ethernet start)"],
        ["buckets", "196 × 20.5 L · chain 120 m @ 10.08 m/min"],
        ["output @70% fill", "20.84 t/h · 347 kg/min"],
        ["instruments", "SS, ST, PSL, ZS12 + 2 LCPs"],
      ],
      questions: [
        "Resolve density inconsistency in the output table (implies 1.47 kg/L).",
        "Spin-down time after stop?",
      ],
    },
    {
      id: "grainBreak",
      type: "grainBreak",
      name: "GRAIN BREAK",
      tag: "TBC-20",
      status: "new",
      zone: "packaging",
      x: 2192, y: 270, w: 48, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 24, y: 0 }, out: { x: 24, y: 36 } },
      labelAt: { x: -150, y: 8 },
      specs: [["role", "cascade chute slowing falling grain"]],
      questions: ["Pass-through only, or any holdup?"],
    },
    {
      id: "outloadDiverter",
      type: "diverter",
      name: "DIVERTER",
      tag: "52.613.V00",
      status: "new",
      zone: "packaging",
      x: 2200, y: 330, w: 32, h: 32,
      ports: { inputs: ["in"], outputs: ["out1", "out2"] },
      anchors: { in: { x: 16, y: 0 }, out1: { x: 8, y: 24 }, out2: { x: 32, y: 16 } },
      smallLabel: true,
      labelAt: { x: 44, y: -4 },
      specs: [["feedback", "ZS1/ZS2 open-close · XV0 pneumatic"]],
      questions: ["Is routing one diverter, or V00 + V01 in series?"],
    },
    {
      id: "metalBin1",
      type: "metalBin",
      name: "TREATED OUTLOAD METAL BIN 1",
      tag: "52.613.H00",
      status: "new",
      zone: "packaging",
      x: 2120, y: 410, w: 160, h: 172,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 80, y: 0 }, out: { x: 80, y: 162 } },
      fill: 0.35,
      instruments: ["LT"],
      labelAt: { x: 0, y: 198 },
      questions: ["Where does it discharge (truck loadout)?"],
    },
    {
      id: "dischargeStub1",
      type: "stub",
      name: "discharge · TBC",
      tag: "STUB.DISCH1",
      status: "stub",
      zone: "packaging",
      x: 2196, y: 650, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },
    {
      id: "metalBin2",
      type: "metalBin",
      name: "TREATED OUTLOAD METAL BIN 2",
      tag: "52.613.H01",
      status: "new",
      zone: "packaging",
      x: 2350, y: 410, w: 160, h: 172,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 80, y: 0 }, out: { x: 80, y: 162 } },
      fill: 0.12,
      instruments: ["LT"],
      labelAt: { x: 0, y: 198 },
      questions: ["Where does it discharge (truck loadout)?"],
    },
    {
      id: "dischargeStub2",
      type: "stub",
      name: "discharge · TBC",
      tag: "STUB.DISCH2",
      status: "stub",
      zone: "packaging",
      x: 2426, y: 650, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },
    {
      id: "binSegSampler",
      type: "sampler",
      name: "AUTO SAMPLER",
      tag: "TBC-10",
      status: "new",
      zone: "packaging",
      x: 2530, y: 210, w: 60, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 30, y: 0 }, out: { x: 30, y: 36 } },
      smallLabel: true,
      labelAt: { x: -180, y: 40 },
      questions: ["Pass-through (assume yes)?"],
    },
    {
      id: "binSegment",
      type: "bin",
      name: "BIN SEGMENT",
      tag: "TBC-11",
      status: "new",
      zone: "packaging",
      x: 2500, y: 280, w: 120, h: 130,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 60, y: 0 }, out: { x: 60, y: 130 } },
      fill: 0.7,
      instruments: ["LT"],
      labelAt: { x: -15, y: -16 },
      specs: [
        ["volume", "4.51 m³ (3.25 t)"],
        ["extras", "pneumatic hammers (rev L)"],
      ],
      questions: ["Tag mapping: 52.610.H00 or 52.612.H00?"],
    },
    {
      id: "flexiconPreBin",
      type: "bin",
      name: "FLEXICON PRE-BIN",
      tag: "TBC-12",
      status: "relocated",
      zone: "packaging",
      x: 2515, y: 440, w: 90, h: 90,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 45, y: 0 }, out: { x: 45, y: 90 } },
      fill: 0.45,
      instruments: ["LSH", "LSL"],
      labelAt: { x: 120, y: 55 },
      questions: ["Is 52.610.H00 (LSH+LSL) this bin or the bin segment?"],
    },
    {
      id: "vibratingConveyor",
      type: "vibratory",
      name: "VIBRATING CONVEYOR",
      tag: "52.703.L00",
      status: "relocated",
      zone: "packaging",
      x: 2520, y: 560, w: 120, h: 30,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 110, y: 30 } },
      labelAt: { x: -188, y: 2 },
      specs: [["drive", "MDOL (direct-on-line, no ramp)"]],
      questions: ["Confirm tag mapping (52.703.L00?)."],
    },
    {
      id: "flexiconFillingHead",
      type: "fillingHead",
      name: "FLEXICON FILLING HEAD",
      tag: "TBC-13",
      status: "relocated",
      zone: "packaging",
      x: 2585, y: 620, w: 90, h: 70,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 45, y: 0 }, out: { x: 45, y: 70 } },
      labelAt: { x: 105, y: 30 },
      questions: ["Big bag size (m³/kg)?", "Fill time and bag-change time?"],
    },
    {
      id: "rollerScale",
      type: "rollerScale",
      name: "ROLLER CONVEYORS 1-4 + BELT SCALE",
      tag: "52.704.K00",
      status: "relocated",
      zone: "packaging",
      x: 2540, y: 720, w: 180, h: 26,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 90, y: 0 }, out: { x: 170, y: 13 } },
      labelAt: { x: 0, y: 46 },
      specs: [["drives", "C00-C03 all VFD · scale 52.704.K00"]],
    },
    {
      id: "bigBagStub",
      type: "stub",
      name: "filled big bags · out",
      tag: "STUB.BIGBAG",
      status: "stub",
      zone: "packaging",
      x: 2760, y: 729, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },
    {
      id: "concettiSampler",
      type: "sampler",
      name: "AUTO SAMPLER",
      tag: "TBC-14",
      status: "new",
      zone: "packaging",
      x: 3160, y: 200, w: 60, h: 36,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 30, y: 0 }, out: { x: 30, y: 36 } },
      smallLabel: true,
      labelAt: { x: 75, y: 22 },
    },
    {
      id: "concettiMetalRemover",
      type: "metalRemover",
      name: "METAL REMOVER",
      tag: "TBC-15",
      status: "new",
      zone: "packaging",
      x: 3160, y: 270, w: 60, h: 46,
      ports: { inputs: ["in"], outputs: ["out", "waste"] },
      anchors: { in: { x: 30, y: 0 }, out: { x: 30, y: 46 }, waste: { x: 60, y: 23 } },
      labelAt: { x: -230, y: 30 },
      questions: ["Real tag (sheet 52-14 references it)?"],
    },
    {
      id: "metalRejectStub2",
      type: "stub",
      name: "metal reject · TBC",
      tag: "STUB.REJECT2",
      status: "stub",
      zone: "packaging",
      x: 3290, y: 289, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },

    // ================= BAGGING (sheet 52-14) =================
    {
      id: "concettiPreBin",
      type: "bin",
      name: "CONCETTI PRE-BIN",
      tag: "52.705.H00",
      status: "new",
      zone: "bagging",
      x: 3145, y: 350, w: 90, h: 90,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 45, y: 0 }, out: { x: 45, y: 90 } },
      fill: 0.5,
      labelAt: { x: 110, y: 30 },
      specs: [["volume", "~0.72 m³ · LOW confidence read"]],
      questions: ["Confirm volume."],
    },
    {
      id: "concettiScale",
      type: "scale",
      name: "BAGGING SCALE",
      tag: "TBC-16",
      status: "new",
      zone: "bagging",
      x: 3150, y: 470, w: 80, h: 46,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 40, y: 0 }, out: { x: 40, y: 46 } },
      labelAt: { x: -220, y: 30 },
      params: [{ id: "rate", label: "bagging rate", min: 0, max: 15, value: 12, unit: "t/h" }],
      specs: [["rate", "~12 t/h · LOW confidence read · the line's choke point"]],
      questions: ["Confirm sustained t/h.", "Bag size?"],
    },
    {
      id: "concettiFiller",
      type: "filler",
      name: "FILLING & SEWING",
      tag: "TBC-17",
      status: "new",
      zone: "bagging",
      x: 3140, y: 550, w: 100, h: 70,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 50, y: 0 }, out: { x: 50, y: 70 } },
      labelAt: { x: 115, y: 35 },
      specs: [["line", "Concetti Bagging Line 2"]],
    },
    {
      id: "palletising",
      type: "palletiser",
      name: "PALLETISING (COLLAPSED)",
      tag: "TBC-18",
      status: "relocated",
      zone: "bagging",
      x: 3120, y: 660, w: 140, h: 80,
      ports: { inputs: ["in"], outputs: ["out"] },
      anchors: { in: { x: 70, y: 0 }, out: { x: 70, y: 80 } },
      labelAt: { x: -260, y: 40 },
      specs: [
        ["contains", "inline weigher · palletiser conveyors · Concetti Palletiser 2"],
        ["also", "incline/decline rollers · pallet magazines"],
      ],
      questions: ["Anything here worth modelling beyond a bag counter?"],
    },
    {
      id: "palletStub",
      type: "stub",
      name: "bagged product · pallets out",
      tag: "STUB.PALLETS",
      status: "stub",
      zone: "bagging",
      x: 3186, y: 790, w: 8, h: 8,
      ports: { inputs: ["in"], outputs: [] },
      anchors: { in: { x: 4, y: 4 } },
    },
  ],

  connections: [
    // treating
    { from: { machine: "upstreamStub", port: "out" }, to: { machine: "treatMetalRemover", port: "in" }, kind: "product", via: [{ x: 120, y: 64 }, { x: 120, y: 115 }] },
    { from: { machine: "treatMetalRemover", port: "waste" }, to: { machine: "metalRejectStub1", port: "in" }, kind: "waste", tbc: true },
    { from: { machine: "treatMetalRemover", port: "out" }, to: { machine: "treaterBufferBin", port: "in" }, kind: "product" },
    { from: { machine: "treaterBufferBin", port: "out" }, to: { machine: "treatDrumFeeder", port: "in" }, kind: "product" },
    { from: { machine: "treatDrumFeeder", port: "out" }, to: { machine: "treatingElevator", port: "in" }, kind: "product" },
    { from: { machine: "treatingElevator", port: "out" }, to: { machine: "treaterPreBin", port: "in" }, kind: "product" },
    { from: { machine: "treaterPreBin", port: "out" }, to: { machine: "batchTreater", port: "in" }, kind: "product" },
    { from: { machine: "chemStub", port: "out" }, to: { machine: "batchTreater", port: "chemIn" }, kind: "chemical" },
    { from: { machine: "batchTreater", port: "wasteOut" }, to: { machine: "wasteWaterIbc", port: "in" }, kind: "waste" },
    { from: { machine: "batchTreater", port: "out" }, to: { machine: "treaterAfterBin", port: "in" }, kind: "product" },
    { from: { machine: "treaterAfterBin", port: "out" }, to: { machine: "scalpingScreen", port: "in" }, kind: "product" },
    { from: { machine: "scalpingScreen", port: "waste" }, to: { machine: "discardBin", port: "in" }, kind: "waste" },
    // treating -> packaging (the cross-zone product run)
    { from: { machine: "scalpingScreen", port: "out" }, to: { machine: "inletDrumFeeder2", port: "in" }, kind: "product", via: [{ x: 1310, y: 715 }] },
    // packaging infeed
    { from: { machine: "proBoxStation", port: "out" }, to: { machine: "inletDrumFeeder1", port: "in" }, kind: "product" },
    { from: { machine: "inletDrumFeeder1", port: "out" }, to: { machine: "liftConveyor", port: "in1" }, kind: "product" },
    { from: { machine: "inletDrumFeeder2", port: "out" }, to: { machine: "liftConveyor", port: "in2" }, kind: "product" },
    { from: { machine: "liftConveyor", port: "out" }, to: { machine: "topConveyor", port: "in" }, kind: "product", tbc: true, via: [{ x: 1440, y: 808 }, { x: 1440, y: 166 }] },
    // branch B: outload metal bins
    { from: { machine: "topConveyor", port: "outBuffer" }, to: { machine: "outloadBufferBin", port: "in" }, kind: "product" },
    { from: { machine: "outloadBufferBin", port: "out" }, to: { machine: "packagingElevator", port: "in" }, kind: "product" },
    { from: { machine: "packagingElevator", port: "out" }, to: { machine: "grainBreak", port: "in" }, kind: "product" },
    { from: { machine: "grainBreak", port: "out" }, to: { machine: "outloadDiverter", port: "in" }, kind: "product" },
    { from: { machine: "outloadDiverter", port: "out1" }, to: { machine: "metalBin1", port: "in" }, kind: "product" },
    { from: { machine: "outloadDiverter", port: "out2" }, to: { machine: "metalBin2", port: "in" }, kind: "product", tbc: true, inactive: true, via: [{ x: 2430, y: 372 }] },
    { from: { machine: "metalBin1", port: "out" }, to: { machine: "dischargeStub1", port: "in" }, kind: "product", tbc: true },
    { from: { machine: "metalBin2", port: "out" }, to: { machine: "dischargeStub2", port: "in" }, kind: "product", tbc: true },
    // branch C: big bag
    { from: { machine: "topConveyor", port: "outBinSeg" }, to: { machine: "binSegSampler", port: "in" }, kind: "product" },
    { from: { machine: "binSegSampler", port: "out" }, to: { machine: "binSegment", port: "in" }, kind: "product" },
    { from: { machine: "binSegment", port: "out" }, to: { machine: "flexiconPreBin", port: "in" }, kind: "product" },
    { from: { machine: "flexiconPreBin", port: "out" }, to: { machine: "vibratingConveyor", port: "in" }, kind: "product" },
    { from: { machine: "vibratingConveyor", port: "out" }, to: { machine: "flexiconFillingHead", port: "in" }, kind: "product", via: [{ x: 2630, y: 605 }] },
    { from: { machine: "flexiconFillingHead", port: "out" }, to: { machine: "rollerScale", port: "in" }, kind: "product" },
    { from: { machine: "rollerScale", port: "out" }, to: { machine: "bigBagStub", port: "in" }, kind: "product" },
    // branch A: Concetti
    { from: { machine: "topConveyor", port: "outConcetti" }, to: { machine: "concettiSampler", port: "in" }, kind: "product", via: [{ x: 3190, y: 180 }] },
    { from: { machine: "concettiSampler", port: "out" }, to: { machine: "concettiMetalRemover", port: "in" }, kind: "product" },
    { from: { machine: "concettiMetalRemover", port: "waste" }, to: { machine: "metalRejectStub2", port: "in" }, kind: "waste", tbc: true },
    { from: { machine: "concettiMetalRemover", port: "out" }, to: { machine: "concettiPreBin", port: "in" }, kind: "product" },
    // bagging
    { from: { machine: "concettiPreBin", port: "out" }, to: { machine: "concettiScale", port: "in" }, kind: "product" },
    { from: { machine: "concettiScale", port: "out" }, to: { machine: "concettiFiller", port: "in" }, kind: "product" },
    { from: { machine: "concettiFiller", port: "out" }, to: { machine: "palletising", port: "in" }, kind: "product" },
    { from: { machine: "palletising", port: "out" }, to: { machine: "palletStub", port: "in" }, kind: "product" },
  ],
};
